<a href="https://colab.research.google.com/github/avinashronanki/Analytics-R/blob/master/tf_serving.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:


import numpy as np
import pandas as pd
import tensorflow as tf

dataset = pd.read_csv('https://raw.githubusercontent.com/futurexskill/ml-model-deployment/main/storepurchasedata_large.csv')

dataset.describe()

dataset.head()

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =.20,random_state=0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(10, activation='relu'),
  tf.keras.layers.Dense(10, activation='relu'),
  tf.keras.layers.Dense(2, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=50)

loss, accuracy =model.evaluate(X_test, y_test)

loss

accuracy

model.summary()

prediction1 = model.predict(sc.transform(np.array([[42,50000]])))[:,1]
 prediction1

predict2 = model.predict(sc.transform(np.array([[20,40000]])))[:,1]
predict2

model.save('customer_behavior_model/1')

!ls

!ls customer_behavior_model

!ls customer_behavior_model/1

from tensorflow.keras.models import load_model

cust_model = load_model('customer_behavior_model/1/')

prediction3 = cust_model.predict(sc.transform(np.array([[42,50000]])))[:,1]
 prediction3

predict4 = model.predict(sc.transform(np.array([[20,40000]])))[:,1]
predict4

from tensorflow.keras.models import load_model

cust_model = load_model('customer_behavior_model/1/')

prediction3 = cust_model.predict(sc.transform(np.array([[42,50000]])))[:,1]
 prediction3

predict4 = model.predict(sc.transform(np.array([[20,40000]])))[:,1]
predict4

!zip -r customermodel.zip customer_behavior_model

from google.colab import files

!ls

files.download('customermodel.zip')



In [1]:

import numpy as np
import pandas as pd
import tensorflow as tf

dataset = pd.read_csv('https://raw.githubusercontent.com/futurexskill/ml-model-deployment/main/storepurchasedata_large.csv')

dataset.describe()

dataset.head()

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =.20,random_state=0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [2]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(10, activation='relu'),
  tf.keras.layers.Dense(10, activation='relu'),
  tf.keras.layers.Dense(2, activation='softmax')
])


In [3]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(X_train, y_train, epochs=50)

In [5]:

loss, accuracy =model.evaluate(X_test, y_test)

10/10 [==============================] - 0s 1ms/step - loss: 0.1085 - accuracy: 0.9550


In [6]:
loss

0.10845602303743362

In [8]:
accuracy

0.9549839496612549

In [ ]:


model.summary()

In [10]:
prediction1 = model.predict(sc.transform(np.array([[42,50000]])))[:,1]
prediction1


array([0.5723339], dtype=float32)

In [11]:

predict2 = model.predict(sc.transform(np.array([[20,40000]])))[:,1]
predict2

array([0.00880246], dtype=float32)

In [12]:

model.save('customer_behavior_model/1')

Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: customer_behavior_model/1/assets


In [13]:
from tensorflow.keras.models import load_model # loading the model 

cust_model = load_model('customer_behavior_model/1/')


In [15]:
prediction3 = cust_model.predict(sc.transform(np.array([[42,50000]])))[:,1]
prediction3



array([0.5723339], dtype=float32)

In [16]:
predict4 = model.predict(sc.transform(np.array([[20,40000]])))[:,1]
predict4

array([0.00880246], dtype=float32)

In [17]:
!zip -r customermodel.zip customer_behavior_model

  adding: customer_behavior_model/ (stored 0%)
  adding: customer_behavior_model/1/ (stored 0%)
  adding: customer_behavior_model/1/assets/ (stored 0%)
  adding: customer_behavior_model/1/saved_model.pb (deflated 88%)
  adding: customer_behavior_model/1/variables/ (stored 0%)
  adding: customer_behavior_model/1/variables/variables.index (deflated 64%)
  adding: customer_behavior_model/1/variables/variables.data-00000-of-00001 (deflated 54%)


In [18]:
from google.colab import files

In [19]:
files.download('customermodel.zip')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>